language: generic
dist: bionic
sudo: required

install:
  - sudo apt-get install tidy

script: 
  - ./check.sh

after_failure:
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_success:
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

